version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      PGHOST: 0.0.0.0
      PGPORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge  